### ISSUE TITLE
About BodyPartAttentionLoss

### ISSUE THREAD

**Issue by zhaojieting** [VlSomers/bpbreid#19]
Hello, thanks for your briliant contribution!
I encounterd a confusing problem. When I using BodyPartAttentionLoss as my loss function, the generated mask can't differentiate between left leg and right leg,  left arm  and right arm.  Have you encountered same problems? How did you solved that ?

**Comment by zhaojieting** [comment]
Thanks a lot in advance!

**Comment by VlSomers** [comment]
Dear @zhaojieting, I indeed encountered this issue, the model is not very good at telling apart right and left parts. One solution is to only use parts that are vertically aligned, such as 'five_v' instead of 'eight'. I'm not sure why the model cannot tell the difference between left and right, if it has to do with the training scheme, the data augmentation or anything else, this is still an open issue!

**Comment by zhaojieting** [comment]
Thanks for your infomation, which is quite helpful !
