### ISSUE TITLE
There was an issue replicating the results of the source code on the occluded_duke dataset

### ISSUE THREAD

**Issue by zaibrua** [VlSomers/bpbreid#46]
When testing the occluded_duke dataset, the process is always terminated in the last output phase. The exit code is interrupted by signal 9:SIGKILL (137)

[Configuration file.txt](https://github.com/user-attachments/files/17783956/Configuration.file.txt)

**Comment by VlSomers** [comment]
Hi @zaibrua, this often happens because of memory overflow issue, unfortunately all test samples features are computed and kept in memory at the same time for performance evaluation (to be optimized in the future), therefore it requires a lot of memory. Can you try to allocate more memory to your run?

**Comment by zaibrua** [comment]
Okay, I understand now, thank you for clarifying, Up.
Duplicate of #
